/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author nadya
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnQueueAdminHomeToAdminQueue = new javax.swing.JButton();
        btnLogOutAdminHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cukurukukBG/12.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnQueueAdminHomeToAdminQueue.setText("Queue");
        btnQueueAdminHomeToAdminQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueueAdminHomeToAdminQueueActionPerformed(evt);
            }
        });
        getContentPane().add(btnQueueAdminHomeToAdminQueue, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 230, 60));

        btnLogOutAdminHome.setText("jButton1");
        btnLogOutAdminHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutAdminHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOutAdminHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 530, 230, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQueueAdminHomeToAdminQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueueAdminHomeToAdminQueueActionPerformed
        AdminQueue queueadminhometoadminqueue = new AdminQueue();
        queueadminhometoadminqueue.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQueueAdminHomeToAdminQueueActionPerformed

    private void btnLogOutAdminHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutAdminHomeActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to LOG OUT?", "Select", JOptionPane.YES_NO_OPTION);
        if(a == 0){
            FirstUI hometofirstui = new FirstUI();
            hometofirstui.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogOutAdminHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOutAdminHome;
    private javax.swing.JButton btnQueueAdminHomeToAdminQueue;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
