/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author nadya
 */
public class Service extends javax.swing.JFrame {

    /**
     * Creates new form Service
     */
    public Service() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBookNowServiceToFormBooking = new javax.swing.JButton();
        btnServiceToAboutUs = new javax.swing.JButton();
        btnServiceToHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cukurukukBG/7.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnBookNowServiceToFormBooking.setText("booknow");
        btnBookNowServiceToFormBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookNowServiceToFormBookingActionPerformed(evt);
            }
        });
        getContentPane().add(btnBookNowServiceToFormBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 660, 250, 70));

        btnServiceToAboutUs.setText("aboutus");
        btnServiceToAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiceToAboutUsActionPerformed(evt);
            }
        });
        getContentPane().add(btnServiceToAboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, 140, 50));

        btnServiceToHome.setText("home");
        btnServiceToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiceToHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnServiceToHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 110, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnServiceToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiceToHomeActionPerformed
        Home servicetohome = new Home();
        servicetohome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnServiceToHomeActionPerformed

    private void btnServiceToAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiceToAboutUsActionPerformed
        AboutUs servicetoaboutus = new AboutUs();
        servicetoaboutus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnServiceToAboutUsActionPerformed

    private void btnBookNowServiceToFormBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookNowServiceToFormBookingActionPerformed
        try (BufferedReader br = new BufferedReader(new FileReader("service_details.txt"))) {
            String line;
            String username = Nama.getInstance().getUsername();
            boolean usernameFound = false;

            while ((line = br.readLine()) != null) {
                String[] details = line.split("\\|");
                if (details.length >= 2 && details[1].equals(username)) {
                    usernameFound = true;
                    break;
                }
            }

            if (usernameFound) {
                JOptionPane.showMessageDialog(null, "Anda sudah memesan layanan ini sebelumnya.",
                        "Warning", JOptionPane.OK_OPTION);
            } else { 
                FormBooking booknowservicetoformbooking = new FormBooking();
                booknowservicetoformbooking.setVisible(true);
                this.dispose();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnBookNowServiceToFormBookingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Service().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookNowServiceToFormBooking;
    private javax.swing.JButton btnServiceToAboutUs;
    private javax.swing.JButton btnServiceToHome;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
